version: "3.2"
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    nfldb:
        container_name: 'nfldb'
        build:
           context: .
        volumes:
            - "./:/code"
        command: python
        depends_on:
            - postgres

        #env_file: .env-nfldb
        
        # nfldb reads the following environment variables:
        # POSTGRES_USER
        # POSTGRES_HOST
        # POSTGRES_DATABASE
        # POSTGRES_PASSWORD
        # POSTGRES_PORT
        # POSTGRES_TIMEZONE
