version: "3.2"
services:
    postgres:
        container_name: 'nfldb-postgres'
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    nfldb:
        container_name: 'nfldb'
        build:
           context: .
        depends_on:
            - postgres
        volumes:
            - "./:/code"
        command: python
